/*
 * generated by Xtext
 */
package org.eclipselabs.swedit.turtle;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TurtleRuntimeModule extends org.eclipselabs.swedit.turtle.AbstractTurtleRuntimeModule {

}
