/*
 * generated by Xtext
 */
package org.eclipselabs.swedit.turtle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TurtleUiModule extends org.eclipselabs.swedit.turtle.ui.AbstractTurtleUiModule {
	public TurtleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
