/*
* generated by Xtext
*/
package org.eclipselabs.swedit.jenarules.ui.contentassist;

import org.eclipselabs.swedit.jenarules.ui.contentassist.AbstractJenaRulesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JenaRulesProposalProvider extends AbstractJenaRulesProposalProvider {

}
