/*
* generated by Xtext
*/
package org.eclipselabs.swedit.turtle.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TurtleAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipselabs/swedit/turtle/parser/antlr/internal/InternalTurtle.tokens");
	}
}
