/*
 * generated by Xtext
 */
package org.eclipselabs.swedit.jenarules;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JenaRulesRuntimeModule extends org.eclipselabs.swedit.jenarules.AbstractJenaRulesRuntimeModule {

}
