/*
* generated by Xtext
*/
package org.eclipselabs.swedit.jenarules.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JenaRulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipselabs/swedit/jenarules/parser/antlr/internal/InternalJenaRules.tokens");
	}
}
