/*
* generated by Xtext
*/
package org.eclipselabs.swedit.turtle.ui.contentassist;

import org.eclipselabs.swedit.turtle.ui.contentassist.AbstractTurtleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TurtleProposalProvider extends AbstractTurtleProposalProvider {

}
