/*
* generated by Xtext
*/
package org.eclipselabs.swedit.turtle.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class TurtleTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
