/*
 * generated by Xtext
 */
package org.eclipselabs.swedit.jenarules.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JenaRulesUiModule extends org.eclipselabs.swedit.jenarules.ui.AbstractJenaRulesUiModule {
	public JenaRulesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
